### ISSUE TITLE
Support image build args

### ISSUE THREAD

**Issue by tim-bm** [Place1/kloudlib#7]
When building an image via the App api, it would be great if it supports build args to be injected to the docker file. 

https://github.com/Place1/kloudlib/blob/master/packages/archetypes/app.ts#L244

It looks fairly simple, I will make a pull request for it.

**Comment by Place1** [comment]
Hey, this can already be done:

```
new App('my-app', {
  src: {
    context: './some/path',
    args: {
      // ...
      key: 'value'
    }
  }
})
```

please reopen if you have any issues.
