### ISSUE TITLE
Support the service port to be configurable

### ISSUE THREAD

**Issue by tim-bm** [Place1/kloudlib#8]
In some use-cases, the service port might be good to be other than 80 to stick with the convention, e.g. 5432 for Postgres.  Can we add configuration for this?

https://github.com/Place1/kloudlib/blob/master/packages/archetypes/app.ts#L441

**Comment by Place1** [comment]
I’d recommend using the “@kloudlib/postgresql” package instead!

The app archetype is best suited for web servers.
